apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: opa-policy-check
spec:
  params:
    - name: policy
      type: string
    - name: input
      type: string
    - name: query
      type: string
      default: data.cicd.allow

  workspaces:
    - name: output

  steps:
    - name: opa-eval
      image: openpolicyagent/opa:1.x
      command: ["opa"]
      args:
        - eval
        - --format=json
        - --data
        - $(workspaces.output.path)/$(params.policy)
        - --input
        - $(workspaces.output.path)/$(params.input)
        - $(params.query)